language: julia

os:
  - linux
  - osx

branches:
  only:
    - master
  
julia:
  - 1.6
  - 1.5.2
  - 1.0.6
  - nightly

matrix:
  allow_failures:
    - julia: nightly
    - julia: 1.5.2
    - julia: 1.0.6


notifications:
  email: false

after_success:
  - julia -e 'using Pkg; Pkg.add("Documenter"); Pkg.add("Coverage");'
  - julia -e 'import LinearAlgebraicRepresentation; cd(dirname(dirname(pathof(LinearAlgebraicRepresentation)))); include(joinpath("docs", "make.jl"))'
  - julia -e 'using Coverage; import LinearAlgebraicRepresentation; cd(dirname(dirname(pathof(LinearAlgebraicRepresentation)))); Codecov.submit(process_folder())'

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs/build
  on:
    branch: master
