name: Documenter
'on':
  push:
    branches:
      - master
    tags: '*'
  pull_request: null
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.6'
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          DOCUMENTER_KEY: '${{ secrets.DOCUMENTER_KEY }}'
        run: julia --project=docs/ docs/make.jl
